project:
  type: website

format:
  revealjs:
    self-contained: true
    theme: moon
    transition: slide
    slide-number: true
    incremental: true
    ratio: 16:9
    plugins: [notes, search, zoom]

editor: visual